### PR TITLE
Add support for external target directories

### PR DESCRIPTION
**Pull request by olofk**
This adds support for setting the TARGETDIR environment variable to use
an external root directory for the targets, to allow keeping the target files
close to the core instead of forking this repo for every new user.

### CODE REVIEW

**Comment by jeremybennett** [comment]
This looks to be a very sensible change to increase the flexibility of the compliance test suite. If there are no objections in the next 24 hours, I propose merging this change.

**Comment by neelgala** [comment]
agree with @jeremybennett

**Comment by jeremybennett** [comment]
Olof - I realize I should have asked you to extend `doc/README.adoc` appropriately to describe this feature. Could you update the pull request with this.

**Comment by olofk** [comment]
I added a line to the documentation now. Please let me know if that is enough

**Comment by jeremybennett** [comment]
Hi Olof. Many thanks. Could you add the ChangeLog and doc/ChangeLog entries and I'll then commit.

**Comment by olofk** [comment]
Done!

**Comment by jeremybennett** [comment]
Hi Olof,

Could you confirm that with your changes the OVPsim and Spike target tests still all pass.

Because of another commit, could you also rebase your patches.

Then I can finally commit them.

**Comment by olofk** [comment]
Rebased and tested that it works fine with OVPsim. Not sure I can find the time to setup spike anytime soon. Any takers on that one?

**Comment by neelgala** [comment]
I could try it out .. but only tomorrow morning.
Will let you know then.

**Comment by neelgala** [comment]
spike passes all tests

**Comment by jeremybennett** [comment]
Thank you both. Now merged.

**Pull request merged**
