### PR TITLE
Added the ability to select a single test from a sute of test for

### PR DESCRIPTION
**Pull request by eroom1966**
Added the ability to pass a set of FLAGS to the target, via a command
line variable to make RISCV_TARGET_FLAGS

Added the ability to select a single test from a suite of tests for compilation and execution

### CODE REVIEW

**Comment by jeremybennett** [comment]
Lee - can you get someone to review this. Perhaps Allen

**Comment by jeremybennett** [comment]
BTW - will need to be rebased on the upstream.

**Comment by allenjbaum** [comment]
I'd like to ensure that this is (or can be made) compatible with riscof

**Comment by jstraus59** [comment]
Allen. 
What?

We cannot stop usability enhancements of the current framework while we start discussing future evolution. 

Riscof is not something we need to be compatible with. 

Riscof is something that _might_ fulfil our future requirements when we agree them. 

So, please lets not stop evolving the current framework. (You have heard of the Osborne effect?)

Thnx
Simon

**Comment by allenjbaum** [comment]
It's a moot issue, since it should work. I certainly have no objection to
be having a method to select a specific test instead of the whole suite - I
think its a good idea.

**Comment by jeremybennett** [comment]
Since this is reviewed, I am happy to merge once the conflicts are addressed.

**Comment by neelgala** [comment]
Just to add.. RISCOF allows selecting of specific tests as well.

**Comment by eroom1966** [comment]
Abandoning this pull request will re-submit

**Pull request closed without merging**
